payment/gateway/urls.py
from django.urls import path
from . import views

app_name = 'gateway'
urlpatterns = [
	path('', views.OfferView.as_view(), name='offer'),
    path('identify', views.Identify.identify, name='identify'),
    path('preview', views.Preview.as_view(), name='preview'),
    path('confirm', views.AuthorizeItem.as_view(), name='confirm'),
]

payment/payment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gateway.urls')),
]

payment/gateway/models.py
from django.db import models

# Create your models here.

payment/gateway/views.py
from django.shortcuts import render
from django.views import View
from .helper import authorize
from django.http import HttpResponseRedirect
from django.http.request import HttpRequest
import json

payment_endpoint = 'http://127.0.0.1:55555'
app_endpoint = 'http://127.0.0.1:8000'

class OfferView(View):
    template = 'gateway/pages/offer.html'

    def get(self, request):
        data = {
            'test': 'test'
        }

        return render(request, self.template, data)

class Identify:
    def identify(self):
        data = {
            'command': 'wapIdentifyUser',
            'username': 'TESTUSER',
            'password': 'SeCrEt',
            'serviceCode': 'VAS0001',
            'userIp': '127.0.0.1',
            'callbackUrl': '%s/preview' % app_endpoint
        }

        auth            = authorize(url=payment_endpoint,data=data)
        response        = json.loads(auth.text)
        redirect_url    = response['redirectURL']

        return HttpResponseRedirect(redirect_url)

class Preview(View):
    template = 'gateway/pages/preview.html'

    def get(self, request):
        data = {
            'command': 'getUser',
            'username': 'TESTUSER',
            'password': 'SeCrEt',
            'serviceCode': 'VAS0001',
            'uid': request.GET['uid']
        }

        auth            = authorize(url=payment_endpoint,data=data)
        response        = json.loads(auth.text)

        user_data = {
            'resultCode': response['resultCode'],
            'resultText': response['resultText'],
            'user_status': response['user']['status'],
            'userIp': response['user']['userIp'],
            'msisdn': response['user']['msisdn'],
            'operatorCode': response['user']['operatorCode'],
            'uid': response['user']['uid'],
        }

        return render(request, self.template, user_data)

class AuthorizeItem(View):
    def get(self, request):
        data = {
            'command': 'wapAuthorize',
            'username': 'TESTUSER',
            'password': 'SeCrEt',
            'serviceCode': 'VAS0001',
            'price': '100',
            'uid': request.GET['uid'],
            'callbackUrl': '%s/result' % app_endpoint
        }

        auth            = authorize(url=payment_endpoint,data=data)
        response        = json.loads(auth.text)
        redirect_url    = response['redirectURL']

        return HttpResponseRedirect(redirect_url)

payment/gateway/templates/gateway/pages/offer.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Offer Page{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Awesome!</h4>
    <p>Every Day New Videos/Movies, Images and E-Books are available to download with a DISCOUNTED price for All Suscbribed Users.</p>
</div>
<div class="row">
    <div class="text-center" style="margin: 0px auto;margin-bottom: 10%">
        <div class="card text-center">
            <div class="card-header">
                Limited Offer
            </div>
            <div class="card-body">
                <h5 class="card-title">Captain Marvel HD (720p)</h5>
                <div class="card" style="width: 30rem">
                    <img class="card-img-top" src="{% static '/assets/images/catainmarvel.jpg' %}" alt="Card image cap">
                </div>
                <p>
                    <br>
                    <a href="{% url 'gateway:identify' %}" class="btn btn-primary">Download Captain Marvel Now</a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

payment/gateway/templates/gateway/pages/preview.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block title %}Offer Page{% endblock %}

{% block content %}
<div class="row">
    <div class="text-center" style="margin: 0px auto;margin-bottom: 10%">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Captain Marvel HD (720p)</h5>
                <div class="card" style="width: 30rem">
                    <img class="card-img-top" src="{% static '/assets/images/preview.jpg' %}" alt="Card image cap">
                </div>
                <p>
                    <br>
                    <a href="{% url 'gateway:confirm' %}?uid={{request.GET.uid}}" class="btn btn-primary">Pay and Automatically Subscribed Now!</a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

payment/gateway/templates/layout/base.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <title>{% block title %}{% endblock %}</title>

    <link href="{% static '/assets/gateway/css/bootstrap.css' %}" rel="stylesheet" />
</head>
<body>
{% include 'layout/include/header.html' %}

<div class="container">
    {% block content %}
        {{ block.super }}
        Welcome To Django 2.1
    {% endblock %}
</div>

<script type="text/javascript" src="{% static '/assets/gateway/js/jquery.slim.js' %}"></script>
<script type="text/javascript" src="{% static '/assets/gateway/js/popper.js' %}"></script>
<script type="text/javascript" src="{% static '/assets/gateway/js/bootstrap.js' %}"></script>
</body>
</html>

payment/gateway/templates/layout/include/header.html
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="margin-bottom: 2%">

    <div class="container">
        <a class="navbar-brand" href="/">RLDWEBSHOP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Videos/Movies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">Images</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">E-Books</a>
                </li>
            </ul>
        </div>
    </div>
</nav>